apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name:  pavithraimage
        image: pavithraacr.azurecr.io/pavithra:v1
        ports:
        - containerPort: 8000
