apiVersion: v1
kind: Service
metadata:
  name: service-demo
spec:
  selector:
    app: front-end
  type: LoadBalancer   # Use LoadBalancer for cloud
  ports:
    - protocol: TCP
      port: 8000       # Service port
      targetPort: 8000 # Container port
      
